### ISSUE TITLE
Not able to run multi-agent demo(e.g. two diggers or MultiMaze) on one machine

### ISSUE THREAD

**Issue by ChristineTzeng** [Microsoft/malmo#494] opened 2017-04-04 19:15 UTC
I tried to run the multi-agent demo with following steps.
1. Launch 2 Minecraft clients with port 10000 and 10001
2. Run MultiMaze.py with role 0 and role 1

However, once I run the role 1 the role 0 seems just halt, and when role1 was shut down the role0 came back. It looks like the running mission never begins.

log of role 0:
python MultiMaze.py
Will run as role 0
Mission 0 --- starting at 0, 200, 0
Waiting for the mission to start....................................................................................................................................................
TimestampedString: 2017-Apr-04 19:07:59.612649, Mission ended abnormally: From Gertrude: Lost contact with the agent
Mission was aborted by server: From Gertrude: Lost contact with the agent
Mission has stopped.
Sleeping to give the clients a chance to reset... done.
Mission 1 --- starting at 32, 200, 0
Waiting for the mission to start...........................................^CTraceback (most recent call last):
  File "MultiMaze.py", line 165, in <module>
    time.sleep(0.1)
KeyboardInterrupt

log of role 1:
python MultiMaze.py --role 1
Will run as role 1
Mission 0 --- starting at 0, 200, 0
Waiting for the mission to start.............................................................................................................................................................^CTraceback (most recent call last):
  File "MultiMaze.py", line 165, in <module>
    time.sleep(0.1)
KeyboardInterrupt

**Comment by DaveyBiggers** [comment] 2017-04-05 07:44
Am closing this as I believe it's a dupe of #420.

**Closed by DaveyBiggers** 2017-04-05 07:44 UTC
