### ISSUE TITLE
Updating LWJGL

### ISSUE THREAD

**Issue by anjaliync** [Microsoft/malmo#642] opened 2017-12-07 19:26 UTC
Hi, I've been having an issue with the Minecraft client specific to LWJGL in that the command key (on Mac) gets stuck once it's pressed (e.g. for tabbing between windows). It seems to have been fixed in the 2.9.3 patch of LWJGL as mentioned [here](https://github.com/LWJGL/lwjgl/issues/43), but the current client uses 2.9.2. Is there a way the dependencies could be updated to use one of the newer versions of LWJGL? If so, how? (not terribly familiar with Gradle, didn't see anything specifically in the `build.gradle` file...)

Thanks!

**Comment by DaveyBiggers** [comment] 2017-12-19 13:25
I'm not sure why Mac is using such an old version - Windows seems to be on 2.9.4. Will investigate this further - it would be useful to update anyway, since there are other fixes in LWJGL that would be handy for docker users (see #644).

**Comment by DaveyBiggers** [comment] 2017-12-20 13:44
Have been digging into ForgeGradle etc - looks like the dependencies are all specified in json files hosted by Mojang - eg here's the file for the version of Minecraft which Malmo currently uses: https://launchermeta.mojang.com/mc/game/12f260fc1976f6dd688a211f1a906f956344abdd/1.11.2.json

If you search that file for lwjgl, you'll see the rules that specify 2.9.4 for Windows and 2.9.2 for OSX - I can only assume there was a regression in the Mac implementation of 2.9.4 that necessitated staying on an older version (or perhaps a bugfix in the Windows implementation that necessitated upgrading for Windows...)

Anyway, it's not too hard to force gradle to use the same version as Windows - find you local copy of this file - it should be in somewhere like users/username/.gradle/caches/minecraft/versionJsons/1.11.2.json - and edit it to remove the osx specific rules. Eg, where you see this:
```
                {
                    "action": "disallow",
                    "os": {
                        "name": "osx"
                    }
                }
```
remove it (remember to remove any trailing commas from the line above, too).
Also remove the whole section relating to lwjgl 2.9.2.

Once you've done this, run launchClient.sh as per normal. If it works, you should see gradle downloading the 2.9.4 files, and hopefully the command key sticking issue will be fixed...

BUT... keep in mind that there was probably a good reason why OSX is on the older version. Keep an eye out for strange behaviour!

The good news is that Minecraft version 1.12 seems to have made the leap to lwjgl version 3, so when we update Malmo to use MC 1.12 (we're currently on 1.11), this problem will go away.

**Comment by DaveyBiggers** [comment] 2018-02-13 17:20
@anjaliync It's been a while since we heard anything, so I'm assuming this solved your issue? Will close this for now, please feel free to reopen it needed.

**Closed by DaveyBiggers** 2018-02-13 17:20 UTC
