### ISSUE TITLE
[Question ]Noise level

### ISSUE THREAD

**Issue by quyle13** [Microsoft/malmo#621] opened 2017-10-29 19:57 UTC
Dear all,

I'm a newbie to Malmo. I'm looking information about how agent deal with noise level ? At the moment, I've created:
 + an agent ( agent_host = MalmoPython.AgentHost())
 + loading xml mission file and starting mission (agent_host.startMission(...))
 + Define list of command ( cmd = ["move 1", "turn 1"]
 + send random command to agent to execute. (agent_host.sendCommand)

If I increase noise level, how it will affect agent to choose a command ?

I try to look for noise level information but I don't see any thing.

Many Thanks,

**Comment by DaveyBiggers** [comment] 2017-10-30 09:52
Can you explain a little more what you are trying to do? What do you mean by noise level in this context?
Cheers,
Dave.

**Comment by quyle13** [comment] 2017-10-30 11:05
Dear Davey,

This is my requirement:
You should provide a solution for an agent without sensory input which takes random
actions.
2.2 Requirements
Sensors: None
Actions: Discrete and noise free. An action takes at least 200 ms to carry out

My solution is:
1. Create an agent ( import MalmoPython; agent_host = MalmoPython.Agent_Host())
2. Loading xml file mission and start mission (agent_host.startMission(my_mission, my_mission_record ))
3. Declare discrete actions (discrete_action_list =["turn 1", "move 1","movenorth 1"....)
4. Taking a random action (agent_host.sendCommand(discrete_action_list[random_index]) 

I'm not sure about noise level in the requirement. Is it a agent configuration attribute ? I try to figure out but still have no idea about it.

Thanks a lot.

Quy

**Comment by DaveyBiggers** [comment] 2017-10-31 11:28
We haven't implemented an agent noise level attribute in Malmo - the agent will always try to act on the command you send it. There is a degree of indeterminacy however, due to the nature of the Minecraft environment. For instance, sending a "move 1" command may or may not result in the agent moving, depending on whether the agent is _able_ to move - there might be a wall blocking the agent, say, or flowing water pushing the agent back. You can mitigate against this (put the agent in a flat arena, don't add any water etc), in which case the only noise would be caused by temporal factors - the asynchronous communication, Minecraft's clock speed, etc. The precise length of time for an action/observation cycle will vary, depending on how long the TCP action message takes to travel, how long the agent takes to process the action, how quickly the action is reflected in the Minecraft world (which can depend on both the Minecraft client and server processes and the communication between them), and how quickly the observation TCP message is returned. But under typical operating conditions, 200ms should easily cover all of that, so if you are allowing 200ms after each `sendCommand` call, you can effectively describe the system as "noise free". So if that's what you are after, no special work is required.

If you want to _add_ noise, you can program it directly on your side - for example, I seem to recall that the Arcade Learning Environment allows you to specify the probability that sending a new action actually repeats the previous action instead.

Does this answer your question?

**Comment by DaveyBiggers** [comment] 2017-11-17 11:34
It's been a while, so I'm closing this - but please reopen if you still have questions about this.

**Closed by DaveyBiggers** 2017-11-17 11:34 UTC
