### ISSUE TITLE
Exception in closing of MissionRecord: boost::filesystem::remove:

### ISSUE THREAD

**Issue by Vorigin** [Microsoft/malmo#619] opened 2017-10-28 09:20 UTC
Exception in closing of MissionRecord: boost::filesystem::remove: 另一个程序正在使用此文件，进程无法访问。: ".\mission_records\45e111d1-8782-4d3c-aa2b-fbf20e816cf1\commands.txt"
Exception in closing of MissionRecord: boost::filesystem::remove: 另一个程序正在使用此文件，进程无法访问。: ".\mission_records\84de38d3-7eb8-4136-bf95-ee6f43b1d38a\commands.txt"
Error starting mission: unidentifiable C++ exception

**Comment by DaveyBiggers** [comment] 2017-10-30 09:54
Can you give us any more information? Steps to reproduce? What OS you are running on, etc?

**Comment by DaveyBiggers** [comment] 2017-11-17 11:41
I'm closing this because without any extra information there's nothing much we can do. If this is still a problem, please reopen and give us a more detailed report.

**Closed by DaveyBiggers** 2017-11-17 11:41 UTC

**Comment by byorxyz** [comment] 2017-12-23 19:35
Hi, I'm getting the same error while I was running sample missions. I'm running it on Windows.

PS C:\Users\ahkim\Desktop\Malmo-0.31.0-Windows-64bit_Python3.6\Malmo-0.31.0-Windows-64bit_Python3.6\Python_Examples>  python tabular_q_learning.py
Loading mission from ../Sample_missions/cliff_walking_1.xml

Map 0 - Mission 1 of 150:
Exception in closing of MissionRecord: boost::filesystem::remove: The process cannot access the file because it is being used by another process: ".\mission_records\5b7ddd24-1306-4cb2-8c59-76738cf8299f\commands.txt"
Exception in closing of MissionRecord: boost::filesystem::remove: The process cannot access the file because it is being used by another process: ".\mission_records\6854c00c-435f-4a44-9556-eb19c2ce213f\commands.txt"
Error starting mission: Failed to find an available client for this mission - tried all the clients in the supplied client pool.
