### ISSUE TITLE
Does 'tp' command supports orientations?

### ISSUE THREAD

**Issue by gliese581gg** [Microsoft/malmo#562] opened 2017-06-21 03:32 UTC
I want to teleport the agent with specific yaw

However tp command with (x y z yaw pitch) parameter does not work.

Is there another way to do this?

**Comment by gliese581gg** [comment] 2017-06-21 14:45
I found it~

It was 'setYaw <degree>'

**Comment by katja-hofmann** [comment] 2017-06-24 12:01
Hi @gliese581gg - thank you for reporting this, and for providing the workaround. The expected behavior is that yaw is respected in the tp command. I'll re-open this for now so that we remember to look into this.

**Comment by DaveyBiggers** [comment] 2017-07-05 12:40
@gliese581gg is correct - the `AbsoluteMovementCommands` include separate commands for setting position, yaw and pitch - there is no command to set the x/y/z/yaw/pitch atomically.
See the documentation here: http://microsoft.github.io/malmo/0.21.0/Schemas/MissionHandlers.html#type_AbsoluteMovementCommand
(apologies for old version in the docs - but AbsoluteMovementCommand hasn't changed since 0.21.0)

The tp command "respects" the yaw in that it won't change the yaw/pitch, so it's possible to set the yaw and then teleport. But perhaps there should be a new command for setting everything at once. If this would be desirable, please open a new issue as a feature request - am closing this one.

**Closed by DaveyBiggers** 2017-07-05 12:40 UTC
