### ISSUE TITLE
import MalmoPython ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by bluejay94** [microsoft/malmo#857] opened 2020-01-19 03:04 UTC
I'm having this problem...

tried to run tutorial through cmd(PythonExamples) and
import MalmoPython
'ImportError: DLL load failed: The specified module could not be found' error message came out

1. used pre-built release for Windows
Malmo-0.37.0-Windows-64bit_withBoost_Python3.6.zip

2. I followed 'Installing dependencies on Windows (automated)'
https://github.com/microsoft/malmo/blob/master/doc/install_windows.md

3. MalmoPython.lib is in my Python_Example folder

**Comment by Fan-Yi-Ming** [comment] 2020-02-24 04:18
mee too

**Comment by Fan-Yi-Ming** [comment] 2020-02-24 04:20
Have you run successfully now？

**Comment by bluejay94** [comment] 2020-02-26 01:28
Now it works. 
I think there are some issues in recent version of malmo
 
try using the older version.(0.35.6)
 
It works well...
 
-----Original Message-----

**Comment by DaveyBiggers** [comment] 2020-03-02 14:19
This is a dupe of #854 - closing this one so we can focus information in just one place.

**Closed by DaveyBiggers** 2020-03-02 14:19 UTC
