### ISSUE TITLE
Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_

### ISSUE THREAD

**Issue by quistuipater** [Microsoft/malmo#470] opened 2017-02-18 00:50 UTC
Error reported when launching Python, C++, and Java examples on macOS 10.12.3:

`Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_ `

**Comment by ericljiang** [comment] 2017-02-21 16:57
See #445

**Comment by DaveyBiggers** [comment] 2017-02-28 12:27
Am closing this - as @ericljiang points out this is a duplicate of #445. The problem is due to the fact that the Mac binaries on our release page were built against El Capitan rather than Sierra, and the version of boost is not binary compatible between the two. Going forwards we'll make sure we use static linking for boost in our release binaries, but for now, building from source should fix this. It should be very easy on the Mac: https://github.com/Microsoft/malmo/blob/master/doc/build_macosx.md

**Closed by DaveyBiggers** 2017-02-28 12:27 UTC
