### ISSUE TITLE
Stale mission elements linger around on restart

### ISSUE THREAD

**Issue by okkhoy** [Microsoft/malmo#490] opened 2017-03-27 22:30 UTC
Steps to reproduce:
- create a mission where you place a specific block (in my case one from: `["redstone_block", "emerald_block", "lapis_block", "cobblestone", "gold_block", "quartz_block"]` at random) anywhere in the environment, 
- send `quit` command to end the mission
- redraw the mission with same logic as above
- notice that the previous block(s) are not cleared, but they are retained in the environment

If I am supposed to "search" for a specific block, it fails due to other rogue blocks being present.

**Comment by J-F-B-M** [comment] 2017-03-28 15:13
Have you tried [`forceWorldReset`](http://microsoft.github.io/malmo/0.17.0/Documentation/classmalmo_1_1_mission_spec.html#abf25f4e5c92fbb91069c71843ce4fa80)?
In XML this would likely be [`forceReset`](http://microsoft.github.io/malmo/0.17.0/Schemas/MissionHandlers.html#element_DefaultWorldGenerator) in any Generator.

**Comment by okkhoy** [comment] 2017-03-28 15:34
I send the `quit` command just before the mission starts, further when I make an API call to `forceWorldReset`, the mission fails to start and the agent quits.
Am I missing something?
Can you please give an example of `forceRest` in the Generator? I am not too sure I understood the second line.

**Comment by okkhoy** [comment] 2017-03-28 15:49
@J-F-B-M ok! i managed to figure out the forceReset in the generator from one of the examples.

However, the agent quits with max retries elapsed error.

**Comment by okkhoy** [comment] 2017-03-29 08:20
Well, even on `forceReset`, the blocks from previous runs remain. (I just had to give a longer time before the mission began to get force reset to work)

**Comment by DaveyBiggers** [comment] 2017-03-29 09:04
Hi @okkhoy, this behaviour is by design - generating fresh worlds in Minecraft is a slow business, so for rapid turnaround between missions we reuse the existing world, provided it matches the requested one. Where we need to reset changes made in the previous mission, we tend to do this by drawing a volume of air blocks in the drawing decorator - this will erase any extra blocks that were placed. Many of the samples use this technique.

The `forceReset` flag forces creation of a brand new Minecraft world, which should guarantee a clean environment, but adds a considerable overhead to the start of each mission. I'd only use it if the air-drawing is insufficient - eg if the agent has been allowed to mine, etc.

"I send the quit command just before the mission starts" - I'm not sure why you'd want to do this? Sounds like it might be the cause of some of the other issues you are seeing (forceReset not working, max retries elapsed error)?

Am closing this issue but please do open a new one for any other problems you are experiencing.

**Closed by DaveyBiggers** 2017-03-29 09:04 UTC
