### ISSUE TITLE
Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_

### ISSUE THREAD

**Issue by Kopsahlong** [Microsoft/malmo#447] opened 2017-01-22 04:32 UTC
When I try to run run_mission.py, I get this error...

Traceback (most recent call last):
  File "run_mission.py", line 20, in <module>
    import MalmoPython
ImportError: dlopen(/Users/Krista/Desktop/CS 270/Malmo-0.19.0-Mac-64bit/Python_Examples/MalmoPython.so, 2): Symbol not found: __ZNK5boost16re_detail_10620031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /Users/Krista/Desktop/CS 270/Malmo-0.19.0-Mac-64bit/Python_Examples/MalmoPython.so
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /Users/Krista/Desktop/CS 270/Malmo-0.19.0-Mac-64bit/Python_Examples/MalmoPython.so

I'm working on a mac, and this is the version of python I'm using....

Python 2.7.13 (default, Jan 21 2017, 22:42:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

pretty sure it's 64 bit. I also ran with /usr/bin/python run_mission.py

**Comment by exfoxz** [comment] 2017-01-22 11:15
Also running into the same problem with the pre-built release with Mac 64 bit...

**Comment by gbmksquare** [comment] 2017-01-22 11:49
Also ran into this problem on macOS Sierra 10.2.2 (official).

Tried building from source after seeing #445, and it works for me.

**Comment by DaveyBiggers** [comment] 2017-01-25 10:51
Closing this as it is a duplicate of #445.

**Closed by DaveyBiggers** 2017-01-25 10:51 UTC
