### ISSUE TITLE
Feature Request: Reward for hitting mob

### ISSUE THREAD

**Issue by OfriHarlev** [Microsoft/malmo#537] opened 2017-05-22 19:58 UTC
Ability to give reward for hitting mob

**Comment by DaveyBiggers** [comment] 2017-06-02 13:29
Closed in #545.
See hit_test.py sample for a demo.
Can assign different rewards to different entities, and also use the usual reward-distribution stuff - should be fairly flexible.

Note that the reward only counts if the entity's damage source was the player - ie if a pig dies because the agent pushed it into lava, the cause of damage will be lava, not the player, so the player won't get the reward.

**Closed by DaveyBiggers** 2017-06-02 13:29 UTC
