### ISSUE TITLE
persistent worlds fail

### ISSUE THREAD

**Issue by TGlas** [Microsoft/malmo#332] opened 2016-09-11 21:04 UTC
I cannot load worlds, no idea since when exactly. This worked back in July. I have the following line in my mission.xml file:

`<FileWorldGenerator src="[absolute-path-to-world]" />`

After start-up of my C++ client I receive the following exception:

`Mission ended abnormally: Server world-creation handler failed to create a world: Minecraft could not load [absolute-path-to-world] - is it a valid saved world?`

Two really odd things happen:

1. Minecraft actually loads the world correctly, I can play it manually.
2. A new world directory `TEMP_[id]` is created in `Minecraft/run/saves/`, while I expected the system to use the existing world directory...?

The world works correctly in single player mode. To be sure I tried three different worlds. May this be a version problem, since Malmo is still based on Minecraft 1.8 as far as I can tell?

More constructive question: What's the best way to create a "standard generated Minecraft world" and to make sure the agent keeps playing this very same world across many sessions? How to create the world, how to reference it later on? I guess the FileWorldGenerator is the answer to the second part, but I am unsure about world creation. Do I have to create it with an old version of the game? Is creating a single player world the way to go at all? Should I create it programmatically and rename the TEMP directory? Or am I missing something?

**Comment by TGlas** [comment] 2016-09-12 07:54
Follow up: I switched to:

```
<DefaultWorldGenerator seed="1001" forceReset="false" destroyAfterUse="false" />
```

since with both booleans set to false the documentation promises to keep the world around. However, I get strange behavior again. The worlds in `Minecraft/run/saves/` are named without the `TEMP` prefix, however, each run creates a new copy of the very same world. Hence also this setting does not allow me to continue with the agent in an existing world it has experienced before. Sounds like a bug to me.

**Comment by DaveyBiggers** [comment] 2016-09-12 09:53
Hi Tobias, this is by design. `DefaultWorldGenerator` does what it says - it creates a default world - the same as you'd get in Minecraft by clicking on "create new world" and using the default options. It will create a new world each time you run.

The behaviour you are seeing with `FileWorldGenerator` is also by design. The intention was to keep your saved world somewhere separate - with your source code, say - and pass that to the generator. Then, rather than use the original, it will copy that file into the Minecraft saves folder, and use the copy. (Which will then either get deleted or not, once the mission has ended, depending on whether `destroyAfterUse` is set.) This is because, for the majority of use cases, researchers expect to be able to run an experiment over and over, and have it start from the same state each time. It would be very bad for the changes to be written back.

It sounds like you want something else - a version of `FileWorldGenerator` that runs from the original, not the copy, so that any alterations the agent makes to its environment are preserved. You can fudge this by setting `destroyAfterUse` to false, and copying the new file manually, but this will be a total pain since the filenames are generated randomly. It would be better if we added a feature to enable this behaviour.

Your `Mission ended abnormally: Server world-creation handler failed to create a world: Minecraft could not load [absolute-path-to-world] - is it a valid saved world?` message sounds like a bug though - what was the path you were passing in? You say Malmo loads it successfully, and then reports the error? I'll look into this.

**Comment by TGlas** [comment] 2016-09-12 12:05
You exactly got my point, I simply wanted (and expected) different behavior. I value the possibility to reproduce experiments, but I'd also welcome an "open ended" experiment format. For example, when testing navigation behavior based on an iteratively built map then I don't want to start from scratch each time, instead I want to maintain a non-trivial map across sessions. The workaround of copying the world files should work for now, since I can assume that there is only one world in the `saves` folder. Alternatively I can pick the most recent one. Of course, it is still a hack and I'd appreciate a proper solution.

For the `FileWorldGenerator` issue, since I apparently misunderstood the concept, I was passing an absolute path to a world located in the `./Minecraft/run/saves/` folder. I had previously copied that world from my `~/Library/Application Support/minecraft/saves` folder (where the game stores all single player worlds). The name did not start with `TEMP`. I have tried different worlds with different names, e.g., `normalworld`.

**Comment by DaveyBiggers** [comment] 2016-09-12 15:03
Okay, have added a feature request in #341.

As for the `FileWorldGenerator` issue, this seems to be a bug - looks like a mistake in the code that tests whether the world loaded successfully (it claims it didn't, even when it did).
Thanks for spotting this - I'll add a new issue for that too, and close this one.
Cheers.

**Closed by DaveyBiggers** 2016-09-12 15:03 UTC
