### ISSUE TITLE
Build Failed - unable to download minecraftforge:forgeSrc

### ISSUE THREAD

**Issue by wending8** [Microsoft/malmo#547] opened 2017-06-04 17:45 UTC
After downloading the pre-built version 0.22.0 on Windows and following the "Launching Minecraft with our Mod" instructions, I receive the following build failed error after running ".\launchClient.bat":

============================================
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\Documents\Project Malmo\Malmo-0.22.0-Windows-64bit\Minecraft\build.gradle' line: 57

* What went wrong:
A problem occurred configuring root project 'Minecraft'.
> Could not resolve all dependencies for configuration ':forgeGradleMc'.
   > Could not find net.minecraftforge:forgeSrc:1.8-11.14.3.1543.
     Searched in the following locations:
         http://files.minecraftforge.net/maven/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.po
m
         http://files.minecraftforge.net/maven/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.ja
r
         https://repo1.maven.org/maven2/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.pom
         https://repo1.maven.org/maven2/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.jar
         https://libraries.minecraft.net/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.pom
         https://libraries.minecraft.net/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc-1.8-11.14.3.1543.jar
         file:/C:/Users/User/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc
-1.8-11.14.3.1543.pom
         file:/C:/Users/User/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeSrc/1.8-11.14.3.1543/forgeSrc
-1.8-11.14.3.1543.jar
         file:/C:/Users/User/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1543/snapshot/20141130/forge
Src-1.8-11.14.3.1543.jar
         file:/C:/Users/User/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1543/snapshot/20141130/forge
Src.jar
     Required by:
         com.microsoft.MalmoMod:Minecraft:0.22.0
=============================================================

The build is successful when I run the command for version 0.21.0. Any suggestions? Thank you in advance.

**Comment by wending8** [comment] 2017-06-04 19:25
*Solved

It was a firewall access issue.

**Comment by mariomeissner** [comment] 2017-06-05 21:13
Well thank you for this post tho!  I had the same issue. You helped me out there haha.
Running with sudo bypassed firewall 😄

**Comment by mariomeissner** [comment] 2017-06-05 21:19
Well I have the same issue, and disabling firewall did not help. 
In fact, if you look at the links the script is trying to access, they all give 404's back, as if the files it is trying to download don't exist on the specified urls.

**Comment by DaveyBiggers** [comment] 2017-06-06 10:49
This seems to be a problem with Forge - hopefully they will get it fixed soon, but in the meantime we'll look into workarounds. I don't think it's to do with Malmo 0.22 vs 0.21 - gradle caches its dependencies, so if forgeSrc has been downloaded successfully in the past, it should continue to work unless the cache is cleared. New installations of Malmo will experience this problem - we're reproduced it here and on our continuous build server.

**Comment by mariomeissner** [comment] 2017-06-06 11:36
Thanks for the confirmation. Let's hope they fix it soon.

**Comment by OneCivilization** [comment] 2017-06-09 04:54
I encountered the same problem, hoping it get fixed soon.

**Comment by DaveyBiggers** [comment] 2017-06-09 13:48
Well, it looks like I owe Forge an apology... the problem seems to have been caused by some code I added into `build.gradle` myself, though quite why it's causing the problem remains a bit of a mystery...
We will release new binaries that contain this fix in due course, but in the meantime, the fix can be applied manually fairly easily as follows:

1.  Find `build.gradle` inside the Minecraft folder.
2.  Either replace it with the latest version from master - https://github.com/Microsoft/malmo/blob/master/Minecraft/build.gradle - or edit it manually to remove the `afterEvaluate` section (around line 48).

Alternatively, manually creating a file called `runMC.sh` (or `runMC.bat` on Windows) inside the Minecraft folder also seems to "fix" things.

Hopefully this should get everyone back up and running - do let me know if not!

**Comment by DaveyBiggers** [comment] 2017-06-09 16:05
FWIW, I think the issue is as follows:
If you look at the list in the error message, (under where it says `Searched in the following locations`), you can see that, after failing to download the files, it looks in the gradle cache for them.
These files get put in the cache by the `setupDecompWorkspace` gradle task - so the broken links are a red herring: with everything working "normally", the files are _generated_, not downloaded.

Unfortunately, the `afterEvaluate` code I added apparently forces gradle to resolve the `forgeGradleMc` dependencies _before_ these files have been generated, leading to the error.

If these files are already cached, of course, this is fine. And once `runMC.sh` exists, the code never runs again, so even trashing the gradle cache won't reproduce the error if `runMC.sh` exists. All of which nicely masks the real issue...

**Comment by mariomeissner** [comment] 2017-06-10 08:26
Can confirm that the latest `build.gradle` from `master` solves the issue.

**Comment by OneCivilization** [comment] 2017-06-11 07:02
@DaveyBiggers Removing the afterEvaluate section in build.gradle solved the problem. Thanks

**Comment by DaveyBiggers** [comment] 2017-07-10 14:34
Fixed by removing the afterEvaluate section.

**Comment by katja-hofmann** [comment] 2017-07-16 20:57
The pre-built release of 0.22 for windows still has this bug. Copying the latest build.gradle over the one in the downloaded release fixes the issue, but the release needs to be updated.

**Comment by DaveyBiggers** [comment] 2017-08-25 16:05
I've re-uploaded the 0.22 windows binaries with this fix - haven't done the same for the other builds, but ideally people should be using 0.30 by now.

**Closed by DaveyBiggers** 2017-08-25 16:05 UTC
Labels: P3

**Comment by AlessandroSigna** [comment] 2021-05-04 15:47
Hi all, the problem is here again

```
Could not resolve all dependencies for configuration ':forgeGradleMc'.
> Could not find forgeSrc.jar (net.minecraftforge:forgeSrc:1.11.2-13.20.0.2228).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/net/minecraftforge/forgeSrc/1.11.2-13.20.0.2228/forgeSrc-1.11.2-13.20.0.2228.jar
```

The searched jar has an invalid url, it returns 404

**Comment by CocoTheOwner** [comment] 2021-05-05 13:37
Bump
