### ISSUE TITLE
ImportError: No module named MalmoPython

### ISSUE THREAD

**Issue by ayyucedemirbas** [Microsoft/malmo#385] opened 2016-10-24 15:09 UTC
![malmopython](https://cloud.githubusercontent.com/assets/8023150/19650770/20a56774-9a13-11e6-9349-b2b64a7e9c79.png)
I have tried to build tutorial_1.py . But I got this error message.
I use Linux Mint. How can I find MalmoPython module?
Thanks!

**Comment by jwflammer** [comment] 2016-10-26 01:26
@ayyucedemirbas  It should be in your python examples folder, then from there you should be able to add it to your users paths.

**Comment by DaveyBiggers** [comment] 2016-10-26 11:07
If there is no MalmoPython.so in your Python_examples folder then it would indicate that you've downloaded the source, rather than installing a pre-built release. If you downloaded the source, you'll also need to build it - see the docs for details.

**Comment by ayyucedemirbas** [comment] 2016-10-27 20:24
![cannot_open](https://cloud.githubusercontent.com/assets/8023150/19783821/0f7b95f0-9c9c-11e6-972d-c08611382675.png)

Hello!

Thanks for your replies. 
https://github.com/Microsoft/malmo => I downloaded this as a .zip file 
https://github.com/Microsoft/malmo/releases => And I downloaded Malmo-0.18.0-Linux-Debian-8.6-64bit.zip 
I followed the instructions at install_linux.md 
I copied /Desktop/Malmo-0.18.0-Linux-Debian-8.6-64bit/Python_Examples MalmopPython.so to Desktop/malmo-master/Malmo/samples/Python_examples
And I tried to build tutorial_1.py
But I got this error message "ImportError: libboost_chrono.so.1.55.0: cannot open shared object file: No such file or directory "
What's the reason of that?

Thank you so much!

**Comment by avisingh599** [comment] 2016-11-07 23:04
I am facing a similar issue on Ubuntu 16.04, the error for me is
`ImportError: libboost_date_time.so.1.61.0: cannot open shared object file: No such file or directory`

I see a solution suggested [here](https://github.com/Microsoft/malmo/issues/179) but involves building from source. Is there any way to get the pre-compiled binaries working?

**Comment by DaveyBiggers** [comment] 2016-12-08 13:22
@avisingh599 the problem is that the pre-compiled binaries were built against a different version of boost to the one on your machine. We've been looking at ways to make this simpler (see #392) but there's no easy fix from our end. On your machine, you have essentially two options - either upgrade (or downgrade) your boost to match the version we built against, or build Malmo yourself against your boost installation.

I'd recommend the second option - building Malmo is very simple on Linux - just follow the instructions here - https://github.com/Microsoft/malmo/blob/master/doc/build_linux.md - it shouldn't take long at all.

The issue you mentioned - #179 - is specifically for _older_ OSs like Debian 7 and Ubuntu 12, where it is necessary to build boost. You shouldn't need to worry about that for Ubuntu 16.04.

**Comment by avisingh599** [comment] 2016-12-08 13:56
Yep, I ultimately ended up building Malmo from source.

**Comment by DaveyBiggers** [comment] 2016-12-08 15:24
Great, I shall close this issue then, and if @ayyucedemirbas is still having problems that aren't captured elsewhere we can open a new issue for that.

**Closed by DaveyBiggers** 2016-12-08 15:24 UTC
