### ISSUE TITLE
Malmo does not launch (jaxb error not resolved)

### ISSUE THREAD

**Issue by feliskatus99** [Microsoft/malmo#746] opened 2018-08-26 12:20 UTC
When I run the launchClient command, the process stops in the middle 

[ant:xjc]   line 451 of file:/C:/Users/김나영/Downloads/Malmo-0.35.6-Windows-64bit_withBoost_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
[ant:xjc] [ERROR] src-resolve: 'ServerQuitWhenAnyAgentFinishes' 이름을 'element declaration' 구성 요소로 분석할 수 없습 니다.
[ant:xjc]   line 452 of file:/C:/Users/김나영/Downloads/Malmo-0.35.6-Windows-64bit_withBoost_Python3.6/Minecraft/src/main/resources/Mission.xsd
[ant:xjc]
:jaxb FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\김나영\Downloads\Malmo-0.35.6-Windows-64bit_withBoost_Python3.6\Minecraft\build.gradle' line: 164

* What went wrong:
Execution failed for task ':jaxb'.
> unable to parse the schema. Error messages should have been provided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.17 secs

:jaxb FAILED

FAILURE: Build failed with an exception.

### --> How do I solve this???
* Where:
Build file 'C:\Users\김나영\Downloads\Malmo-0.35.6-Windows-64bit_withBoost_Python3.6\Minecraft\build.gradle' line: 164

* What went wrong:
Execution failed for task ':jaxb'.
> unable to parse the schema. Error messages should have been provided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by AndKram** [comment] 2018-08-28 08:27
Could you try installing Malmo under c:\Malmo? i.e no spaces or unicode characters in the path. Jaxb is looking for the schema files and lack of support for unicode directory names is a known issue. Thanks.

**Comment by AndKram** [comment] 2018-09-07 11:01
Think this is a duplicate of #452. Please re-open if changing path to ascii only does not help.

**Closed by AndKram** 2018-09-07 11:01 UTC
